Docker
trivago/hamara pull request #13
Opened 2021-03-30 09:57 UTC by mrlioncub

New working file for Docker Hub 

* update Dockerfile
* update README.md

working container https://hub.docker.com/r/mrlioncub/hamara

2021-04-05 14:18 UTC, jorgelbg requested changes
Hi @mrlioncub thank you very much for your contribution 🎉! This PR definitively improves the Docker setup for this project.

I left a few small comments, mostly around using `trivago/hamara` for the Docker image (instead of the fork) in the badges/documentation.

> I also think that we should automatically build & push a new Docker image every time that a new release is tagged, but we can track this in a different issue/PR.

2021-04-05 14:18 UTC, jorgelbg commented on README.md
> +docker run --rm mrlioncub/hamara
nit: Now that we have the `trivago/hamara` image, we should use it.

```suggestion
docker run --rm trivago/hamara
```

2021-04-06 03:37 UTC, mrlioncub reviewed
Everything is fine, but we need to change README.md:
mrlioncub/hamara -> trivago/hamara

2021-05-03 08:51 UTC, jorgelbg approved these changes
Great work @mrlioncub, I will go ahead and merge this. I think we're in good shape now to build a docker image as part of the release process when a new version is tagged.

2021-05-03 10:52 UTC, merged